# Generated by Django 5.0.6 on 2025-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_embedding', models.JSONField()),
                ('retrieved_content_ids', models.JSONField()),
                ('similarity_scores', models.JSONField()),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('response_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('project', 'Project'), ('skill', 'Skill'), ('experience', 'Experience'), ('personal_info', 'Personal Info'), ('testimonial', 'Testimonial'), ('faq', 'FAQ')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('content_text', models.TextField()),
                ('embedding_vector', models.JSONField()),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type'], name='rag_service_content_f62ba2_idx'), models.Index(fields=['content_id'], name='rag_service_content_9b00ad_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
    ]
